function listUni()
{
$("#wrapperGH").show();
$("#wrapperWBAP").hide();
$("#wrapperWBICT").hide();
$("#wrapperWBEP").hide(); 
$("#wrapperWBNMS").hide();
$("#wrapperWBEMC").hide();
$("#wrapperWBAH").hide();
$("#wrapperWBUSF").hide();  
$("#wrapperWBBAL").hide();
$("#wrapperWBAFFV").hide();
$("#wrapperWBSSJU").hide();  
}
function AllPros()
{
$("#wrapperGH").hide();
$("#wrapperWBAP").show();
$("#wrapperWBICT").hide();
$("#wrapperWBEP").hide(); 
$("#wrapperWBNMS").hide();
$("#wrapperWBEMC").hide();
$("#wrapperWBAH").hide();
$("#wrapperWBUSF").hide();  
$("#wrapperWBBAL").hide();
$("#wrapperWBAFFV").hide();
$("#wrapperWBSSJU").hide();  
}
function ICTPro()
{
$("#wrapperGH").hide();
$("#wrapperWBAP").hide();
$("#wrapperWBICT").show();
$("#wrapperWBEP").hide(); 
$("#wrapperWBNMS").hide();
$("#wrapperWBEMC").hide();
$("#wrapperWBAH").hide();
$("#wrapperWBUSF").hide();  
$("#wrapperWBBAL").hide();
$("#wrapperWBAFFV").hide();
$("#wrapperWBSSJU").hide();  
}
function EPPros()
{
$("#wrapperGH").hide();
$("#wrapperWBAP").hide();
$("#wrapperWBICT").hide();
$("#wrapperWBEP").show(); 
$("#wrapperWBNMS").hide();
$("#wrapperWBEMC").hide();
$("#wrapperWBAH").hide();
$("#wrapperWBUSF").hide();  
$("#wrapperWBBAL").hide();
$("#wrapperWBAFFV").hide();
$("#wrapperWBSSJU").hide();  
}
function NMSPro()
{
$("#wrapperGH").hide();
$("#wrapperWBAP").hide();
$("#wrapperWBICT").hide();
$("#wrapperWBEP").hide(); 
$("#wrapperWBNMS").show();
$("#wrapperWBEMC").hide();
$("#wrapperWBAH").hide();
$("#wrapperWBUSF").hide();  
$("#wrapperWBBAL").hide();
$("#wrapperWBAFFV").hide();
$("#wrapperWBSSJU").hide();  
}
function EMCPro()
{
$("#wrapperGH").hide();
$("#wrapperWBAP").hide();
$("#wrapperWBICT").hide();
$("#wrapperWBEP").hide(); 
$("#wrapperWBNMS").hide();
$("#wrapperWBEMC").show();
$("#wrapperWBAH").hide();
$("#wrapperWBUSF").hide();  
$("#wrapperWBBAL").hide();
$("#wrapperWBAFFV").hide();
$("#wrapperWBSSJU").hide();  
}
function AHPro()
{
$("#wrapperGH").hide();
$("#wrapperWBAP").hide();
$("#wrapperWBICT").hide();
$("#wrapperWBEP").hide(); 
$("#wrapperWBNMS").hide();
$("#wrapperWBEMC").hide();
$("#wrapperWBAH").show();
$("#wrapperWBUSF").hide();  
$("#wrapperWBBAL").hide();
$("#wrapperWBAFFV").hide();
$("#wrapperWBSSJU").hide();  
}
function USFPro()
{
$("#wrapperGH").hide();
$("#wrapperWBAP").hide();
$("#wrapperWBICT").hide();
$("#wrapperWBEP").hide(); 
$("#wrapperWBNMS").hide();
$("#wrapperWBEMC").hide();
$("#wrapperWBAH").hide();
$("#wrapperWBUSF").show();  
$("#wrapperWBBAL").hide();
$("#wrapperWBAFFV").hide();
$("#wrapperWBSSJU").hide();  
}
function BALPro()
{
$("#wrapperGH").hide();
$("#wrapperWBAP").hide();
$("#wrapperWBICT").hide();
$("#wrapperWBEP").hide(); 
$("#wrapperWBNMS").hide();
$("#wrapperWBEMC").hide();
$("#wrapperWBAH").hide();
$("#wrapperWBUSF").hide();  
$("#wrapperWBBAL").show();
$("#wrapperWBAFFV").hide();
$("#wrapperWBSSJU").hide();  
}
function AFFVPro()
{
$("#wrapperGH").hide();
$("#wrapperWBAP").hide();
$("#wrapperWBICT").hide();
$("#wrapperWBEP").hide(); 
$("#wrapperWBNMS").hide();
$("#wrapperWBEMC").hide();
$("#wrapperWBAH").hide();
$("#wrapperWBUSF").hide();  
$("#wrapperWBBAL").hide();
$("#wrapperWBAFFV").show();
$("#wrapperWBSSJU").hide();  
}
function SSJUPro()
{
$("#wrapperGH").hide();
$("#wrapperWBAP").hide();
$("#wrapperWBICT").hide();
$("#wrapperWBEP").hide(); 
$("#wrapperWBNMS").hide();
$("#wrapperWBEMC").hide();
$("#wrapperWBAH").hide();
$("#wrapperWBUSF").hide();  
$("#wrapperWBBAL").hide();
$("#wrapperWBAFFV").hide();
$("#wrapperWBSSJU").show();  
}			
